import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { FolderCode, NotepadText } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-h-svh h-screen flex justify-center">
          <div className="max-w-md w-full bg-green-300 font-mono font-semibold text-green-500 flex flex-col relative">
            <nav className="w-full flex justify-between p-4 text-black">
              <div className="flex gap-1">
                <h1>Dar Notes</h1>
                <NotepadText />
              </div>
              {/* <button>show</button> */}
              <div className=""><NavBar /></div>
            </nav>
            <div className="flex size-full relative items-center justify-center bg-green-200">
              {children}
            </div>
            <footer className="flex items-center justify-center p-4 gap-1 text-black">
              <p>Made by ShadyDar</p>
              <FolderCode />
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}